### ISSUE TITLE
Any planned integration with Atria

### ISSUE THREAD

**Issue by ohpauleez** [arximboldi/immer#12]
First and foremost, fantastic work here and your ICFP paper was a nice read.

I was curious if you have given any thought to your previous work on Atria and building additional capabilities (or even compatibility) with immer.

**Comment by arximboldi** [comment]
Hi Paul!

Tthanks a lot for the compliments, that's very encouraging!

And, yeah, I have given it a thought to the Atria question---in some way, this project is just a "follow up" on that one...  The two clearest ways of potential interaction are:

1. Transducers. Basically, overloading Atria's `reduce` using `immer::for_each_chunk_p` for very efficient transformations of immutable sequences. There is the open question of doing buffered lazy transformations a-la Clojure, which I think might fit somewhere at the intersection of the two libraries.

2. There is this module in Atria called `funken`, which we never really talked about [1] but is maybe one of the most interesting modules there. The goal of that library is to fill the impedance mismatch between immutable data in the "single atom" architecture and imperative subsystems that consume or update the data (e.g. traditional UIs with frameworks like Qt). This library was indeed conceptually conceived when we were building that library, because without efficient immutable data-structures it is hard to scale apps written with those tools.

Now, what will actually happen in that direction? I personally doubt that much will happen inside Atria itself. My involvement with it is in "maintenance mode", there is noone inside Ableton developing features for it, and there are almost no active users that I know of [2].

In the mid-term I would like to extract the transducers module as a separate library so it is easier to consume and better documented. Also a good chance to reimplement it exploring different approaches [3]. This might happen within the a year from now or so---I want to do the associative containers for `immer` first, so it depends on how long that takes.

I would like to build a new library in the direction of Funken too, but I am not sure I would just take the `atria::funken` API "as-is". Over the last couple of years I have been quite inspired by Reagent and would like to achieve something with some syntactic similarities, but adapted to the problems we have in the C++ world. I have lots of ideas of what that could entail, but I am afraid of turning it into vaporware if I talk too much about them already 😄  Some of the fundamentals in Funken might be useful to implement that---they are a bit like reactive cursors---but this needs more research...  I hope I can find some generous sponsors to be able to tackle this problem with all the focus it deserves.

Anyways...and sorry for the long response---I think I just used this as a brain-dump 💩. I must admit it also made me super excited to see that some Cognitec people are following this project. Is Cognitec exploring things in the native/systems technologies world?

---

[1] (@brentshields did a talk once at Ableton about a Clojure implementation he made first, not sure if that was ever recorded there. The C++ version has significant conceptual differences.

[2] Someone from Ableton told me recently they are using the `match()` module, but admittedly the recent work on variant deconstruction from @SuperV1234 is more complete in almost every sense (excepting deducing a `?:`-operator-like common type for the result of the expression, which is on the other hand kind of a niche feature).

[3] C++14 minimum requirement, plus change some of the details of how the state wrapping process works...

**Comment by arximboldi** [comment]
Hi @ohpauleez, should I close the issue?

**Comment by ohpauleez** [comment]
Hi @arximboldi - thanks for the detailed/thoughtful response and checking in!
You can do whatever you like with the issue :)  I mostly wanted you to know that you have a fan and that I care to see the vision/story evolve.
