### ISSUE TITLE
c++20: make all constexpr

### ISSUE THREAD

**Issue by bansan85** [arximboldi/immer#138]
In C++20, all const function in `std::vector` are constexpr.

I know the library is c++14 and it will probably need `constexpr new` in c++ 20. Plus, probably like you, I don't actually have enough time to implement it.

I'm just creating this issue to know if it could be a good idea to integrate this feature in a future roadmap ?

**Comment by arximboldi** [comment]
Hi!

With my understanding on the limtiations of constexpr new, I think it would be of limited interest for this library, since you would not be able to create a container and have it then move into runtime world. Also, because of structural sharing and the internal reference counting, I am not sure how far things would actually work at all. 

I think that, at least theoretically, you could maybe get the containers work to implement a constexpr algorithm and then output another result. However, these containers provide most value when there is concurrency or interactivity involved, so I am not sure it would be a great advantage to use immer over std in constexpr world, at least for now.

This is therefore low priority.

For constexpr containers you may find this library interesting: https://github.com/serge-sans-paille/frozen
