### ISSUE TITLE
Fix exit-time destructor warning

### ISSUE THREAD

**Issue by chuim** [arximboldi/immer#161]
This snippet from `immer/immer/detail/hamts/champ.hpp` causes an exit-time destructor warning from clang:
```C++
    static const champ& empty()
    {
        static const champ empty_{
            node_t::make_inner_n(0),
            0,
        };
        return empty_;
    }
```
I'll create a pull request to suggest addressing it similarly to what's discussed in this [stack-overflow question](https://stackoverflow.com/questions/14335494/how-to-deal-with-exit-time-destructor-warning-in-clang).

**Comment by arximboldi** [comment]
Thanks! While the warning is mostly incouous (it may have an effect though if empty maps or sets are created in the global destruction sequence) it makes sense to fix it.

Hmmm. Beware of creating an unnecessary intermediate node for the champ. I think this is simplest and most performant:

```cpp
    static champ empty()
    {
        static const auto node = [] {
            auto n = node_t::make_inner_n(0);
            n->inc();
            return n;
        }();
        return {node, 0};
    }
```

You may encounter the need for a similar fix in `rbtree.hpp` and `rrbtree.hpp`.

**Comment by chuim** [comment]
What I'd propose would follow that question I mentioned previously (the only change is in the 3rd line):
```
    static const champ& empty()
    {
        static champ& empty_ = *new champ{
            node_t::make_inner_n(0),
            0,
        };
        return empty_;
    }
```
So nothing would change as for the creation of the object except for using the heap to avoid the destructor call. What do you think?

Thanks for the pointer to the other files; I'll check them too.

**Comment by arximboldi** [comment]
@chuim yes, looking at the link you sent, I assumed that was gonna be your suggestion :)

However, my solution uses the fact that we are now ok with never deallocating the object to slightly improve the performance of this function. The previous solution (and your suggested) touches the refcount of the `node_t` created there whenever `empty()` is used to create a new map or set, because the `champ` object is copied in the caller. With my suggestion we allow RVO to happen and not touch the refcount of the `node_t` at all :slightly_smiling_face:

Anyway, too many details... I'd suggest just using my snippet. I could maybe even try it myself if you wanna, or I'll just wait for your PR so you can make sure it really fixes your warning and it does not break anything on your end.

**Comment by chuim** [comment]
I tried using your code verbatim on `champ.hpp` but that causes tests failures. I also tried mimicking it for `rbtree.hpp` and `rrbtree.hpp` and got more failures. As I'm not an actual user of immer code so I'm just trying to "pattern match" what you did and am lost on how to fix these errors.

As you offered to try addressing this yourself, I'd be happy to let you take over. Alternatively I could send a PR with the sub-optimal heap-based implementation.

**Comment by arximboldi** [comment]
Hi @chuim, addressed in #163

**Comment by arximboldi** [comment]
For the record, your suggested solution sadly did not work either, since it caused problems when `libgc` is used (because the allocated object is unknown to `libgc` so it would deallocate the nodes...). I ended up doing something different. Give it a try and let me know if it works for you!

**Comment by chuim** [comment]
Thanks so much for doing this! Once issue #162 gets resolved I'll integrate both changes back into our internal codebase and report back.

**Comment by chuim** [comment]
FYI all looks good after the integration. Thanks a lot for your assistance addressing these somewhat nit-picky issues.

**Comment by arximboldi** [comment]
You're welcome!
