### ISSUE TITLE
equivalent of "update all" ?

### ISSUE THREAD

**Issue by BrannonKing** [arximboldi/immer#53]
I was surprised that the for_each methods for immer did not return a new collection. What's the right way to clone my immutable vector whilst modifying each element? Or is there a way to use std::transform with immer? Picture a collection of geometric points where I need to translate them all by the same value.

**Comment by arximboldi** [comment]
Hi @BrannonKing!

I explicitly didn't want to add functional-looking higher order functions because I see that as part of another potential library (something like the transducer stuff from https://github.com/Ableton/atria which I would like to revamp and extract into its own library one of these years) or something like `range-v3`.

The most efficient way to generate a new version of a collection in `immer` is pupulating a new collection using a transient, and iterating the source collection using `for_each`. For example:

```cpp
template <typename T, typename Fn>
immer::vector<T> mapped(const immer::vector<T>& v, Fn && f)
{
    auto r = immer::vector_transient<T>{};
    immer::for_each(v, [&] (auto&& x) {
        r.push_back(fn(x));
    });
    return r;
}
```

Also note that if you are most of the time updating most elements you are not benefiting from the structural-sharing that `immer::vector` provides. In that case, you may as well use `immer::array`. Also, iterating an `immer::array` using _iterators_ is as efficient as using `immer::for_each` (in the case of `immer::vector` and `immer::flex_vector`, there is a potential performance advantage of using `for_each`).

I hope this addresses your question. Cheers!

**Comment by arximboldi** [comment]
To ensure responsive support like this in the future, if you are using Immer in a commercial project, please consider sponsoring the project (via [Patreon](https://www.patreon.com/sinusoidal) or just drop me an email for other agreements :smile: )

**Comment by BrannonKing** [comment]
Yes, I see how to use your transients now. Thanks.

**Comment by arximboldi** [comment]
I just edited the response, since there was a bug in the last line: you need to call `persistent()` to get an immutable version out of a transient.
