### ISSUE TITLE
Storing abstract types

### ISSUE THREAD

**Issue by dgel** [arximboldi/immer#55]
Hi, I want to use immer to store a very simple json-like structure. There are 4 types of values that can be stored, and I want to recur by storing a base class pointer in the collection types.

I figured box would be perfect for storing this, but the compiler doesn't allow storing abstract types in it. Is there a way around this, or is there an accepted alternative way of storing such values?

**Comment by arximboldi** [comment]
Yeah, there is no special support for polymorphism in `box`... it can't really be solved without incurring overhead, the same way that other type erasure libraries do it (i.e. `std::any`, `boost::type_erasure`, `dyno`). However, why do you need a base class? Have you tried designing your problem around `std::variant` instead of class hierarchies?

**Comment by arximboldi** [comment]
Closing the issue since, without any further info, it seems out of soce (use variants, any or type erasure patterns instead.)
