### ISSUE TITLE
dec_unsafe leads to memory leaks?

### ISSUE THREAD

**Issue by swapnilh** [arximboldi/immer#62]
I am having trouble understanding the need for the dec_unsafe function in refcount_policy. This function simply decrements the reference count without returning true if the count drops to 0. So if dec_unsafe is used and the count drops to 0, doesn't this mean that an object has no references but is not freed?

**Comment by arximboldi** [comment]
This is only used in situations where the algorithm can ensure that the count can not go to 0 at some point. For example, when copying an inner node as part of a vector update, we increase the counts of all the children, and then decrease the count of the child that was actually updated, since it is not part of the copy. We know that the count can not go to zero at that point because its parent must be referenced from this thread's stack. Doing things this way saves splitting the increment-children-refcounts loop in two, helping the branch predictor a bit and generating less code. It is for the most part a detail and you should not worry about it :smile:
