### ISSUE TITLE
-Werror=unused-parameter triggers on Release builds

### ISSUE THREAD

**Issue by Bogdan-Morosanu** [arximboldi/immer#66]
When turning warnings into errors and disabling `assert`s in release builds, some function parameters used just in `assert`s get flagged as unused variables and the build fails. My current company is investigating using this library in our production code, so changing the compilation flags is not an option.

I am willing to fix this issue but unsure how to proceed. Could you please provide some short guidance related to this?

**Comment by arximboldi** [comment]
Glad you are looking into using Immer!

Can your company use `-isystem`  or `/I:external` for the include paths of Immer? In this way, warnings coming from the library will not affect your project. That is overall the recommended way to use libraries that you do not control directly.

Otherwise, I would be happy to accept a patch fixing that warning, including adding it to the `immer-dev` target in the CMake file so it is controlled by CI in the future.
