### ISSUE TITLE
Persistent Maps

### ISSUE THREAD

**Issue by jjl** [arximboldi/immer#7]
Hi,

I'm playing with immer for a project at the minute, but i also need immutable maps. I'm considering porting either Clojure's HAMTs or the CHAMP variant. Did you have any plans in this direction or could you give me a little advice on how to go about porting it into the infrastructure you've laid down?

Thanks

**Comment by arximboldi** [comment]
Cool! I am glad that you find this useful.

HAMT's/CHAMP are next on the roadmap once I am done with RRB-Trees (vectors). If everything goes as planned I would start that work myself in March.  

If that is too late for you, I would be happy if you want to try do it yourself... Actually, interesting timing, I am starting now to write a paper with some details about how this library is built. If you give me your email, I can send you a draft when ready so you can try figure a bit better how to make sense of the _policy based_ design and other questions about the code. This may take a few weeks though. If you want, we can also chat a bit about your use-case and other related stuff in the meantime.

Cheers!

**Comment by jjl** [comment]
Hi,

I don't have a fixed timeframe for release, but the project I'm working on (something like datomic, but in c++) needs a few more persistent collections. As I'm most familiar with the implementation of the HAMT, I thought I'd start there.

Other things I anticipate needing over the coming months:
- Sorted maps (not sure what the state of the art is here)
- Sets (clojure's?)
- Sorted sets
- Interval trees ( http://jfla.inria.fr/2010/actes/PDF/bonichon_cuoq.pdf ? )

There's a good list of candidates here: http://cstheory.stackexchange.com/questions/1539/whats-new-in-purely-functional-data-structures-since-okasaki#answer-1550

As I'm not in any particular rush, I'm happy to be without an implementation for a while, either while you do it or while you prepare enough in the way of documentation that I'm able to do it. This is a hobby project, so no commercial pressures :)

**Comment by arximboldi** [comment]
Nice! Having something like Datomic but in C++ is something I fantasized with a few times (and enabling that kind work is one of the motivations behind this library). Ping me if you get to make any progress that you would like to share :smile: 

Sorted maps and sets are also high on the list. Interval trees are interesting. In the domain I worked most on (music software) and `boost::interval_map` gets often used there. But since it is a bit more specialized I will push it a bit down the priority queue :wink: Another interesting data structure that I have been thinking about the last few months is the concurrent snapshotable lock-free tries that Prokopec et al. wrote about in [1]. Not really *immutable*, but persistent and concurrent and potentially very useful for in-memory databases.

Thanks for the pointers!

[1] https://axel22.github.io/publications/concurrent-tries-with-snapshots/

**Comment by arximboldi** [comment]
Hi @jjl,

Sorry I forgot to answer this earlier. Since last time I wrote I did manage to finish writing the paper about immutable vectors and it has been accepted for ICFP'17 😄 If you'd like to take a look before the pre-print is published I can send it you by email (gimme an address I should send it to).

With regards to unordered maps/sets, I have already been doing some of the ground-research work and I would like to start with a prototype CHAMP-based implementation soon.

How is your Datomic-like data-base project going, any interesting results so far?

**Comment by jjl** [comment]
I've been working mostly on stuff in java-space (kotlin) in my spare time recently, so it hasn't gone very far. I'm likely to finish implementing the prototype of this in kotlin for now and i'll look at doing it in c++ later

**Comment by arximboldi** [comment]
Awesome, thanks for the update!

**Comment by calder** [comment]
A big +1 for persistent maps!

Also immer is really cool! Thanks for an awesome project!

**Comment by arximboldi** [comment]
@jjl I managed to upload a preprint of the paper I told you about: https://public.sinusoid.es/misc/immer/immer-icfp17-preprint-00.pdf

**Comment by thedrow** [comment]
I've been looking into porting CHAMP lately and it's pretty complex. I've written some code to figure out what it does but the branching logic is killing me.
See [this](https://github.com/usethesource/capsule/blob/master/capsule-core/src/main/java/io/usethesource/capsule/core/PersistentTrieMap.java#L1081) for example. [This](https://github.com/usethesource/capsule/blob/master/capsule-core/src/main/java/io/usethesource/capsule/core/PersistentTrieMap.java#L1944) is even worse.
Any advice? Is there something that can be done to reduce the branching of CHAMP implementations?

**Comment by ddcc** [comment]
@arximboldi I skimmed through the preprint, looks great! I'm specifically interested in support for maps and sets; have you had a chance to start the CHAMP-based prototype? If not, I'm considering taking a stab at it, though I still need to catch up on the paper and related work.

**Comment by arximboldi** [comment]
@ddcc thanks! I have been studying CHAMP over the last few months and I now have a good idea of how I would implement it, but I had not chance to get into the code yet. Most probably I will start in September, after ICFP. Translating some of the optimizations described in the paper to CHAMP/HAMT is sadly not trivial, due to its sparse nature. I can get more into the details later if you want.

**Comment by arximboldi** [comment]
Just re-read my message, sorry if it sounded a bit negative. I don't want to stop you from making your own implementation if you wanna give it a shot yourself! Let me know if you find something interesting along the way 😄

**Comment by arximboldi** [comment]
Hi! I just merged #19 which I think solves this issue. There is still work to do in this area (transients) but I believe this belongs in a follow up issue. Enjoy!

**Comment by jjl** [comment]
Oh wow, amazing work! I've been using const std maps and copying stuff around a lot the last few days, so this couldn't have come at a better time!

**Comment by arximboldi** [comment]
I'm glad! Btw @jjl, when you have a data-type that you want to treat immutable without copying all the time you may consider `immer::box` as a decent compromise (I have used it in Ewig to treat `std::unordered_map` in an immutable way).

**Comment by jjl** [comment]
Not sure how interesting this is to you, but [bifurcan](https://github.com/lacuna/bifurcan) (Java) is pretty cool and might have some ideas to steal.
